theme = "gruvbox"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
text-width = 80

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-inlay-hints = true

[keys.normal.g]
q = ":reflow"
